# Generated by Django 5.0.5 on 2024-05-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of the payment.",
                        max_digits=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="The payment method used (e.g., credit card, PayPal).",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the payment was created.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
