# Generated by Django 5.0.5 on 2024-05-14 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fabrics", "0001_initial"),
        ("measurements", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.TextField(
                        help_text="Additional specifications for the contract.",
                        max_length=200,
                    ),
                ),
                (
                    "fabric",
                    models.ManyToManyField(
                        help_text="The fabrics included in the contract.",
                        to="fabrics.fabric",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        help_text="The measurement associated with the contract.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measurements.measurement",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order associated with the contract.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with the contract.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
    ]
