# Generated by Django 5.0.5 on 2024-05-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the fabric.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="A description of the fabric."),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The price of the fabric.",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FabricImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="The image file uploaded for the fabric.",
                        upload_to="fabrics/",
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        help_text="The fabric instance associated with the image.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fabrics.fabric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fabric Image",
                "verbose_name_plural": "Fabric Images",
            },
        ),
    ]
